# Dependencies
markdown:            kramdown
highlighter:         rouge

# Permalinks
#
# Use of `relative_permalinks` ensures post links from the index work properly.
permalink:           pretty

# Setup
title:               B. Shine Cho, Ph.D.
tagline:             'Public Administration Scholar investigating local government affairs'
description:         'Public administration, local govenrment, budgeting & financial management,  public participation'
url:                 https://shinecho724.github.io
giturl:				       
baseurl:             ''
paginate:            5
rss:                 https://shinecho724.github.io/atom.xml

# About/contact
author:
  name:             B. Shine Cho
  email:            shine.cho724@gmail.com
  linkedin:         bshinecho
  google_scholar:   https://scholar.google.com/citations?user=ctmX4igAAAAJ&hl=en

# Custom vars
version:             1.0.1

github:
  repo:           https://github.com/kylestratis/kylestratis.github.io
